"""
Constraint generation for Rosetta relaxation.

Generates coordinate constraints for ligand atoms and catalytic residue
contact atoms. Supports self-derived constraints from input geometry
and ref_pdb-based constraints.

Output:
- Human-readable .cst file in Rosetta format
- JSON summary of constraints for programmatic use
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Dict, Any, Optional, Tuple, Set
import json

from fastmpnndesign.config import Contact, CatalyticResidue, ConstraintConfig, CatresCatresContact
from fastmpnndesign.ligand import Ligand, LigandAtom, detect_ligands_from_pdb, detect_metals_from_pdb
from fastmpnndesign.contact_detection import (
    detect_contacts_from_pdb, get_protein_atoms, ProteinAtom, detect_catres_catres_contacts
)
from fastmpnndesign.constants import (
    COORD_CST_STDEV, METAL_CST_STDEV, PRIMARY_CST_STDEV, SECONDARY_CST_STDEV,
    HBOND_CST_STDEV, SALT_BRIDGE_CST_STDEV, PI_STACK_CST_STDEV
)
from fastmpnndesign.utils import iter_pdb_atoms, write_json
from fastmpnndesign.alignment import (
    align_ref_to_input_by_ligand, transform_coordinates, detect_ligand_resname
)
from fastmpnndesign.logging_config import get_logger

logger = get_logger("constraints")


@dataclass
class CoordinateConstraint:
    """Represents a coordinate constraint for an atom."""
    chain: str
    resnum: int
    resname: str
    atom_name: str
    x: float
    y: float
    z: float
    stdev: float
    constraint_type: str  # 'ligand', 'metal', 'catres_primary', 'catres_secondary'
    source: str  # 'self' or 'ref_pdb'

    def to_rosetta_cst(self, anchor_chain: str = "A", anchor_resnum: int = 1) -> str:
        """
        Generate Rosetta coordinate constraint line.

        Format:
        CoordinateConstraint <atom> <res> <anchor_atom> <anchor_res> <x> <y> <z> HARMONIC 0.0 <stdev>

        Note: In practice, we use the virtual root atom (atom 1 of residue 1) as anchor.
        """
        return (
            f"CoordinateConstraint {self.atom_name} {self.resnum}{self.chain} "
            f"CA {anchor_resnum}{anchor_chain} "
            f"{self.x:.3f} {self.y:.3f} {self.z:.3f} HARMONIC 0.0 {self.stdev:.4f}"
        )

    def to_dict(self) -> Dict[str, Any]:
        return {
            'chain': self.chain,
            'resnum': self.resnum,
            'resname': self.resname,
            'atom_name': self.atom_name,
            'x': self.x,
            'y': self.y,
            'z': self.z,
            'stdev': self.stdev,
            'constraint_type': self.constraint_type,
            'source': self.source
        }


@dataclass
class DistanceConstraint:
    """Represents a distance constraint between two atoms."""
    chain1: str
    resnum1: int
    resname1: str
    atom1: str
    chain2: str
    resnum2: int
    resname2: str
    atom2: str
    distance: float
    stdev: float
    constraint_type: str  # 'metal', 'primary', 'secondary'

    def to_rosetta_cst(self) -> str:
        """
        Generate Rosetta distance constraint line.

        Format:
        AtomPair <atom1> <res1> <atom2> <res2> HARMONIC <dist> <stdev>
        """
        return (
            f"AtomPair {self.atom1} {self.resnum1}{self.chain1} "
            f"{self.atom2} {self.resnum2}{self.chain2} "
            f"HARMONIC {self.distance:.3f} {self.stdev:.4f}"
        )

    def to_dict(self) -> Dict[str, Any]:
        return {
            'chain1': self.chain1,
            'resnum1': self.resnum1,
            'resname1': self.resname1,
            'atom1': self.atom1,
            'chain2': self.chain2,
            'resnum2': self.resnum2,
            'resname2': self.resname2,
            'atom2': self.atom2,
            'distance': self.distance,
            'stdev': self.stdev,
            'constraint_type': self.constraint_type
        }


@dataclass
class ConstraintSet:
    """Collection of constraints for a structure."""
    coordinate_constraints: List[CoordinateConstraint] = field(default_factory=list)
    distance_constraints: List[DistanceConstraint] = field(default_factory=list)
    source_pdb: str = ""
    ref_pdb: str = ""

    def to_rosetta_cst_file(self, output_path: Path, anchor_chain: str = "A") -> None:
        """Write constraints to Rosetta .cst file format."""
        lines = []
        lines.append(f"# Constraints generated by fastmpnndesign")
        lines.append(f"# Source PDB: {self.source_pdb}")
        if self.ref_pdb:
            lines.append(f"# Reference PDB: {self.ref_pdb}")
        lines.append("")

        # Coordinate constraints
        if self.coordinate_constraints:
            lines.append("# Coordinate constraints")
            for cst in self.coordinate_constraints:
                lines.append(cst.to_rosetta_cst(anchor_chain=anchor_chain))
            lines.append("")

        # Distance constraints
        if self.distance_constraints:
            lines.append("# Distance constraints")
            for cst in self.distance_constraints:
                lines.append(cst.to_rosetta_cst())
            lines.append("")

        with open(output_path, 'w') as f:
            f.write('\n'.join(lines))

        logger.info(f"Wrote {len(self.coordinate_constraints)} coordinate and "
                    f"{len(self.distance_constraints)} distance constraints to {output_path}")

    def to_summary_json(self, output_path: Path) -> None:
        """Write constraint summary to JSON file."""
        summary = {
            'source_pdb': self.source_pdb,
            'ref_pdb': self.ref_pdb,
            'n_coordinate_constraints': len(self.coordinate_constraints),
            'n_distance_constraints': len(self.distance_constraints),
            'coordinate_constraints': [c.to_dict() for c in self.coordinate_constraints],
            'distance_constraints': [d.to_dict() for d in self.distance_constraints],
            'summary': self._generate_summary()
        }
        write_json(output_path, summary)
        logger.info(f"Wrote constraint summary to {output_path}")

    def _generate_summary(self) -> Dict[str, Any]:
        """Generate summary statistics."""
        coord_by_type = {}
        for c in self.coordinate_constraints:
            if c.constraint_type not in coord_by_type:
                coord_by_type[c.constraint_type] = 0
            coord_by_type[c.constraint_type] += 1

        dist_by_type = {}
        for d in self.distance_constraints:
            if d.constraint_type not in dist_by_type:
                dist_by_type[d.constraint_type] = 0
            dist_by_type[d.constraint_type] += 1

        return {
            'coordinate_by_type': coord_by_type,
            'distance_by_type': dist_by_type
        }


def generate_ligand_coordinate_constraints(
    ligands: List[Ligand],
    metals: List[Ligand],
    stdev: float = COORD_CST_STDEV,
    source: str = "self"
) -> List[CoordinateConstraint]:
    """
    Generate coordinate constraints for all ligand and metal heavy atoms.

    Args:
        ligands: List of ligand molecules.
        metals: List of metal ions.
        stdev: Standard deviation for harmonic constraint.
        source: Source of constraint ('self' or 'ref_pdb').

    Returns:
        List of CoordinateConstraint objects.
    """
    constraints = []

    # Ligand atoms
    for lig in ligands:
        for atom in lig.heavy_atoms:
            constraints.append(CoordinateConstraint(
                chain=lig.chain,
                resnum=lig.resnum,
                resname=lig.resname,
                atom_name=atom.name,
                x=atom.x,
                y=atom.y,
                z=atom.z,
                stdev=stdev,
                constraint_type='ligand',
                source=source
            ))

    # Metal atoms
    for metal in metals:
        for atom in metal.atoms:
            constraints.append(CoordinateConstraint(
                chain=metal.chain,
                resnum=metal.resnum,
                resname=metal.resname,
                atom_name=atom.name,
                x=atom.x,
                y=atom.y,
                z=atom.z,
                stdev=METAL_CST_STDEV,  # Extra tight for metals
                constraint_type='metal',
                source=source
            ))

    logger.debug(f"Generated {len(constraints)} ligand/metal coordinate constraints")
    return constraints


def generate_contact_coordinate_constraints(
    contacts: List[Contact],
    pdb_path: Path,
    source: str = "self"
) -> List[CoordinateConstraint]:
    """
    Generate coordinate constraints for protein atoms in contact with ligands.

    Args:
        contacts: List of detected contacts.
        pdb_path: Path to PDB file to get atom coordinates.
        source: Source of constraint.

    Returns:
        List of CoordinateConstraint objects.
    """
    # Get protein atom coordinates
    protein_atoms = get_protein_atoms(pdb_path, catres_only=False)
    atom_lookup = {}
    for atom in protein_atoms:
        key = (atom.chain, atom.resnum, atom.name)
        atom_lookup[key] = atom

    constraints = []
    seen_atoms: Set[Tuple[str, int, str]] = set()

    for contact in contacts:
        key = (contact.protein_chain, contact.protein_resnum, contact.protein_atom)

        # Skip if already constrained
        if key in seen_atoms:
            continue
        seen_atoms.add(key)

        atom = atom_lookup.get(key)
        if not atom:
            logger.warning(f"Atom not found: {key}")
            continue

        # Determine stdev based on contact type
        if contact.contact_type == 'metal':
            stdev = METAL_CST_STDEV
            cst_type = 'catres_metal'
        elif contact.contact_type == 'primary':
            stdev = PRIMARY_CST_STDEV
            cst_type = 'catres_primary'
        else:
            stdev = SECONDARY_CST_STDEV
            cst_type = 'catres_secondary'

        constraints.append(CoordinateConstraint(
            chain=atom.chain,
            resnum=atom.resnum,
            resname=atom.resname,
            atom_name=atom.name,
            x=atom.x,
            y=atom.y,
            z=atom.z,
            stdev=stdev,
            constraint_type=cst_type,
            source=source
        ))

    logger.debug(f"Generated {len(constraints)} contact coordinate constraints")
    return constraints


def generate_catres_sidechain_constraints(
    pdb_path: Path,
    catres_list: List[CatalyticResidue],
    existing_constraints: Optional[List[CoordinateConstraint]] = None,
    stdev: float = 0.2,
    source: str = "self"
) -> List[CoordinateConstraint]:
    """
    Generate coordinate constraints for ALL catres sidechain heavy atoms.

    This ensures catres that don't have direct ligand contacts are still
    constrained to preserve active site geometry. Avoids duplicating
    constraints that already exist from contact-based generation.

    Args:
        pdb_path: Path to PDB file.
        catres_list: List of catalytic residues to constrain.
        existing_constraints: Already generated constraints to avoid duplicates.
        stdev: Standard deviation for constraints (default 0.2 A - looser than contacts).
        source: Source of constraint ("self" or "ref_pdb").

    Returns:
        List of CoordinateConstraint objects for catres sidechains.
    """
    # Track already-constrained atoms to avoid duplicates
    already_constrained = set()
    if existing_constraints:
        for cst in existing_constraints:
            key = (cst.chain, cst.resnum, cst.atom_name)
            already_constrained.add(key)

    # Build catres lookup
    catres_lookup = {}
    for cr in catres_list:
        key = (cr.chain, cr.resnum)
        catres_lookup[key] = cr

    # Backbone atom names to exclude (only constrain sidechains)
    backbone_atoms = {'N', 'CA', 'C', 'O', 'H', 'HA', 'HA2', 'HA3', 'OXT'}

    constraints = []
    n_skipped = 0

    for atom in iter_pdb_atoms(pdb_path):
        # Only process ATOM records (not HETATM)
        if atom['record_type'] != 'ATOM':
            continue

        atom_name = atom['name']
        resname = atom['resname']
        chain = atom['chain']
        resnum = atom['resnum']

        # Only process catres residues
        if (chain, resnum) not in catres_lookup:
            continue

        # Skip backbone atoms
        if atom_name in backbone_atoms:
            continue

        # Skip hydrogen atoms (names starting with H or digit then H)
        if atom_name.startswith('H') or (len(atom_name) > 1 and atom_name[0].isdigit() and atom_name[1] == 'H'):
            continue

        # Skip if already constrained
        key = (chain, resnum, atom_name)
        if key in already_constrained:
            n_skipped += 1
            continue
        already_constrained.add(key)

        constraints.append(CoordinateConstraint(
            chain=chain,
            resnum=resnum,
            resname=resname,
            atom_name=atom_name,
            x=atom['x'],
            y=atom['y'],
            z=atom['z'],
            stdev=stdev,
            constraint_type='catres_sidechain',
            source=source
        ))

    logger.debug(
        f"Generated {len(constraints)} catres sidechain constraints "
        f"(skipped {n_skipped} already-constrained atoms)"
    )
    return constraints


def generate_distance_constraints_from_contacts(
    contacts: List[Contact]
) -> List[DistanceConstraint]:
    """
    Generate distance constraints from detected contacts.

    Args:
        contacts: List of detected contacts.

    Returns:
        List of DistanceConstraint objects.
    """
    constraints = []

    for contact in contacts:
        # Determine stdev based on contact type
        if contact.contact_type == 'metal':
            stdev = METAL_CST_STDEV
        elif contact.contact_type == 'primary':
            stdev = PRIMARY_CST_STDEV
        else:
            stdev = SECONDARY_CST_STDEV

        constraints.append(DistanceConstraint(
            chain1=contact.ligand_chain,
            resnum1=contact.ligand_resnum,
            resname1=contact.ligand_resname,
            atom1=contact.ligand_atom,
            chain2=contact.protein_chain,
            resnum2=contact.protein_resnum,
            resname2=contact.protein_resname,
            atom2=contact.protein_atom,
            distance=contact.distance,
            stdev=stdev,
            constraint_type=contact.contact_type
        ))

    logger.debug(f"Generated {len(constraints)} distance constraints from contacts")
    return constraints


def generate_distance_constraints_from_catres_catres(
    catres_catres_contacts: List[CatresCatresContact]
) -> List[DistanceConstraint]:
    """
    Generate distance constraints from catres-catres contacts.

    These constraints maintain the interactions between catalytic residues
    (hydrogen bonds, salt bridges, pi-stacking) with tight tolerances.

    Args:
        catres_catres_contacts: List of detected catres-catres contacts.

    Returns:
        List of DistanceConstraint objects.
    """
    constraints = []

    for contact in catres_catres_contacts:
        # Determine stdev based on interaction type
        if contact.interaction_type == 'hbond':
            stdev = HBOND_CST_STDEV
        elif contact.interaction_type == 'salt_bridge':
            stdev = SALT_BRIDGE_CST_STDEV
        elif contact.interaction_type == 'pi_stack':
            stdev = PI_STACK_CST_STDEV
        else:
            stdev = PRIMARY_CST_STDEV  # Default fallback

        constraints.append(DistanceConstraint(
            chain1=contact.chain1,
            resnum1=contact.resnum1,
            resname1=contact.resname1,
            atom1=contact.atom1,
            chain2=contact.chain2,
            resnum2=contact.resnum2,
            resname2=contact.resname2,
            atom2=contact.atom2,
            distance=contact.distance,
            stdev=stdev,
            constraint_type=f"catres_{contact.interaction_type}"
        ))

    logger.debug(
        f"Generated {len(constraints)} distance constraints from catres-catres contacts"
    )
    return constraints


def generate_constraints_self_derived(
    pdb_path: Path,
    catres_list: Optional[List[CatalyticResidue]] = None,
    config: Optional[ConstraintConfig] = None
) -> ConstraintSet:
    """
    Generate constraints from input PDB geometry (self-derived).

    This is the default mode when no ref_pdb is provided.
    Constraints preserve the current geometry of ligands and catres contacts.

    Args:
        pdb_path: Path to input PDB file.
        catres_list: List of catalytic residues for contact detection.
        config: Constraint configuration.

    Returns:
        ConstraintSet with coordinate and distance constraints.
    """
    if config is None:
        config = ConstraintConfig()

    pdb_path = Path(pdb_path)

    # Detect ligands and metals
    ligands = detect_ligands_from_pdb(pdb_path)
    metals = detect_metals_from_pdb(pdb_path)

    # Detect contacts
    contacts = detect_contacts_from_pdb(
        pdb_path,
        catres_list=catres_list,
        primary_cutoff=config.primary_contact_cutoff,
        secondary_cutoff=config.secondary_contact_cutoff,
        metal_cutoff=config.metal_cutoff,
        catres_only=True if catres_list else False
    )

    # Generate constraints
    coord_constraints = []

    # Ligand/metal coordinate constraints
    coord_constraints.extend(
        generate_ligand_coordinate_constraints(
            ligands, metals, stdev=config.coord_cst_stdev, source="self"
        )
    )

    # Contact atom coordinate constraints
    contact_coord_constraints = generate_contact_coordinate_constraints(
        contacts, pdb_path, source="self"
    )
    coord_constraints.extend(contact_coord_constraints)

    # Catres sidechain constraints for ALL catres residues (not just those with contacts)
    # This ensures catres that don't directly contact the ligand are still constrained
    if catres_list:
        catres_sc_constraints = generate_catres_sidechain_constraints(
            pdb_path,
            catres_list,
            existing_constraints=coord_constraints,  # Avoid duplicates
            stdev=SECONDARY_CST_STDEV,  # Looser stdev for non-contact catres
            source="self"
        )
        coord_constraints.extend(catres_sc_constraints)
        if catres_sc_constraints:
            logger.info(
                f"Added {len(catres_sc_constraints)} sidechain constraints for "
                f"catres without direct ligand contacts"
            )

    # Distance constraints from ligand-catres contacts
    dist_constraints = generate_distance_constraints_from_contacts(contacts)

    # Detect and add catres-catres contacts
    catres_catres_contacts = []
    if catres_list and len(catres_list) >= 2:
        catres_catres_contacts = detect_catres_catres_contacts(pdb_path, catres_list)
        catres_catres_dist_constraints = generate_distance_constraints_from_catres_catres(
            catres_catres_contacts
        )
        dist_constraints.extend(catres_catres_dist_constraints)

    constraint_set = ConstraintSet(
        coordinate_constraints=coord_constraints,
        distance_constraints=dist_constraints,
        source_pdb=str(pdb_path)
    )

    # Log summary with catres-catres breakdown
    n_ligand_dist = len(contacts)
    n_catres_catres = len(catres_catres_contacts) if catres_catres_contacts else 0
    logger.info(
        f"Generated self-derived constraints: "
        f"{len(coord_constraints)} coordinate, {len(dist_constraints)} distance "
        f"({n_ligand_dist} ligand-catres, {n_catres_catres} catres-catres)"
    )

    return constraint_set


def generate_constraints_from_ref(
    input_pdb: Path,
    ref_pdb: Path,
    catres_list: Optional[List[CatalyticResidue]] = None,
    config: Optional[ConstraintConfig] = None,
    ligand_resname: Optional[str] = None
) -> ConstraintSet:
    """
    Generate constraints based on reference PDB geometry.

    Uses ref_pdb coordinates as the target geometry for constraints,
    but transforms them into the input_pdb coordinate frame using
    ligand-based alignment. This ensures constraints work correctly
    even if ref_pdb and input_pdb are not pre-aligned.

    The ligand should be identical and fixed between ref_pdb and input_pdb,
    so aligning by ligand HETATM atoms gives a perfect overlay.

    Args:
        input_pdb: Path to input PDB file.
        ref_pdb: Path to reference PDB file with ideal geometry.
        catres_list: List of catalytic residues.
        config: Constraint configuration.
        ligand_resname: Ligand residue name for alignment. If None, auto-detect.

    Returns:
        ConstraintSet with constraints derived from ref_pdb geometry,
        transformed into input_pdb coordinate frame.
    """
    if config is None:
        config = ConstraintConfig()

    input_pdb = Path(input_pdb)
    ref_pdb = Path(ref_pdb)

    # Detect ligand resname if not provided
    if ligand_resname is None:
        ligand_resname = detect_ligand_resname(ref_pdb)
        if ligand_resname is None:
            ligand_resname = detect_ligand_resname(input_pdb)

        if ligand_resname is None:
            logger.warning(
                "No ligand detected for alignment. "
                "Constraints will be in ref_pdb coordinate frame."
            )

    # Compute alignment transformation (ref_pdb -> input_pdb)
    R = None
    t = None
    if ligand_resname:
        try:
            R, t = align_ref_to_input_by_ligand(ref_pdb, input_pdb, ligand_resname)
            logger.info(
                f"Computed ligand-based alignment (ligand: {ligand_resname}) "
                f"to transform ref_pdb constraints to input_pdb coordinate frame"
            )
        except ValueError as e:
            logger.warning(
                f"Could not align by ligand: {e}. "
                "Constraints will be in ref_pdb coordinate frame."
            )

    # Generate constraints from ref_pdb geometry
    constraint_set = generate_constraints_self_derived(
        ref_pdb, catres_list, config
    )

    # Transform coordinate constraints to input_pdb frame
    if R is not None and t is not None:
        for cst in constraint_set.coordinate_constraints:
            # Transform the constraint coordinates
            old_coords = (cst.x, cst.y, cst.z)
            new_coords = transform_coordinates(old_coords, R, t)
            cst.x, cst.y, cst.z = new_coords

        logger.info(
            f"Transformed {len(constraint_set.coordinate_constraints)} "
            f"coordinate constraints to input_pdb frame"
        )

    # Update source information
    constraint_set.source_pdb = str(input_pdb)
    constraint_set.ref_pdb = str(ref_pdb)

    # Update source tag in all constraints
    for cst in constraint_set.coordinate_constraints:
        cst.source = "ref_pdb"

    logger.info(
        f"Generated ref-based constraints from {ref_pdb}: "
        f"{len(constraint_set.coordinate_constraints)} coordinate, "
        f"{len(constraint_set.distance_constraints)} distance"
    )

    return constraint_set


def generate_constraints(
    pdb_path: Path,
    catres_list: Optional[List[CatalyticResidue]] = None,
    config: Optional[ConstraintConfig] = None,
    output_dir: Optional[Path] = None
) -> ConstraintSet:
    """
    Main entry point for constraint generation.

    Generates constraints using either ref_pdb (if provided) or self-derived
    from input PDB geometry.

    Args:
        pdb_path: Path to input PDB file.
        catres_list: List of catalytic residues.
        config: Constraint configuration.
        output_dir: Directory to write constraint files (optional).

    Returns:
        ConstraintSet with all constraints.
    """
    if config is None:
        config = ConstraintConfig()

    # Choose constraint generation mode
    if config.ref_pdb and config.ref_pdb.exists():
        constraint_set = generate_constraints_from_ref(
            pdb_path, config.ref_pdb, catres_list, config
        )
    else:
        constraint_set = generate_constraints_self_derived(
            pdb_path, catres_list, config
        )

    # Write output files if directory provided
    if output_dir:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        cst_file = output_dir / "constraints.cst"
        summary_file = output_dir / "constraints_summary.json"

        # Determine anchor chain from first protein residue
        anchor_chain = "A"
        if constraint_set.coordinate_constraints:
            for cst in constraint_set.coordinate_constraints:
                if cst.constraint_type not in ('ligand', 'metal'):
                    anchor_chain = cst.chain
                    break

        constraint_set.to_rosetta_cst_file(cst_file, anchor_chain=anchor_chain)
        constraint_set.to_summary_json(summary_file)

    return constraint_set


def load_legacy_cst_file(cst_path: Path) -> List[str]:
    """
    Load a legacy Rosetta constraint file.

    Args:
        cst_path: Path to .cst file.

    Returns:
        List of constraint lines.
    """
    with open(cst_path, 'r') as f:
        lines = [line.strip() for line in f if line.strip() and not line.startswith('#')]
    return lines
