"""
SLURM job submission utilities.

Generates sbatch scripts for running fastmpnndesign on HPC clusters.
"""

from pathlib import Path
from typing import List, Optional
import shlex
import sys

from fastmpnndesign.config import RunConfig, SlurmConfig
from fastmpnndesign.utils import ensure_dir
from fastmpnndesign.logging_config import get_logger

logger = get_logger("slurm")

SBATCH_TEMPLATE = """#!/bin/bash
#SBATCH --job-name={job_name}
#SBATCH --output={output_log}
#SBATCH --error={error_log}
#SBATCH --time={time}
#SBATCH --cpus-per-task={cpus}
#SBATCH --mem={mem}
{partition_line}
{extra_directives}

# FastMPNN Design Job
# Generated by fastmpnndesign
# Input PDB: {input_pdb}

echo "Starting fastmpnndesign job at $(date)"
echo "Running on host: $(hostname)"
echo "Working directory: $(pwd)"
echo ""

# Load required modules (customize as needed)
{module_loads}

# Activate conda/virtual environment if needed
{env_activation}

# Set environment variables
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
{extra_env}

# Run fastmpnndesign
{command}

EXIT_CODE=$?

echo ""
echo "Job completed at $(date) with exit code $EXIT_CODE"
exit $EXIT_CODE
"""


def generate_sbatch_script(
    config: RunConfig,
    output_path: Optional[Path] = None,
    job_name: Optional[str] = None,
    module_loads: Optional[List[str]] = None,
    env_activation: Optional[str] = None,
    extra_env: Optional[List[str]] = None,
    extra_directives: Optional[List[str]] = None
) -> Path:
    """
    Generate sbatch script for running fastmpnndesign.

    Args:
        config: Run configuration.
        output_path: Path to write sbatch script. Defaults to output_dir/run.sbatch.
        job_name: SLURM job name. Defaults to "fastmpnn_{prefix}".
        module_loads: List of module load commands.
        env_activation: Environment activation command (e.g., "conda activate myenv").
        extra_env: Additional environment variable exports.
        extra_directives: Additional SBATCH directives.

    Returns:
        Path to generated sbatch script.
    """
    slurm = config.slurm

    # Set defaults
    if output_path is None:
        output_path = config.output_dir / "run.sbatch"
    output_path = Path(output_path)

    if job_name is None:
        job_name = f"fastmpnn_{config.prefix}"

    # Build partition line
    partition_line = ""
    if slurm.partition:
        partition_line = f"#SBATCH --partition={slurm.partition}"

    # Build module loads
    module_loads_str = ""
    if module_loads:
        module_loads_str = "\n".join(f"module load {m}" for m in module_loads)

    # Build env activation
    env_activation_str = ""
    if env_activation:
        env_activation_str = env_activation

    # Build extra env
    extra_env_str = ""
    if extra_env:
        extra_env_str = "\n".join(f"export {e}" for e in extra_env)

    # Build extra directives
    extra_directives_str = ""
    if extra_directives:
        extra_directives_str = "\n".join(f"#SBATCH {d}" for d in extra_directives)

    # Build command
    command = build_command_line(config)

    # Log paths
    log_dir = config.output_dir / "logs"
    ensure_dir(log_dir)
    output_log = log_dir / f"{job_name}_%j.out"
    error_log = log_dir / f"{job_name}_%j.err"

    # Fill template
    script = SBATCH_TEMPLATE.format(
        job_name=job_name,
        output_log=output_log,
        error_log=error_log,
        time=slurm.time,
        cpus=slurm.cpus,
        mem=slurm.mem,
        partition_line=partition_line,
        extra_directives=extra_directives_str,
        input_pdb=config.pdb,
        module_loads=module_loads_str,
        env_activation=env_activation_str,
        extra_env=extra_env_str,
        command=command
    )

    # Write script
    ensure_dir(output_path.parent)
    with open(output_path, 'w') as f:
        f.write(script)

    # Make executable
    output_path.chmod(0o755)

    logger.info(f"Generated sbatch script: {output_path}")

    return output_path


def build_command_line(config: RunConfig) -> str:
    """
    Build command line string from configuration.

    Args:
        config: Run configuration.

    Returns:
        Command line string.
    """
    cmd = ["fastmpnndesign"]

    # Required arguments
    cmd.extend(["--pdb", str(config.pdb)])

    for p in config.params:
        cmd.extend(["--params", str(p)])

    # Output
    cmd.extend(["--output_dir", str(config.output_dir)])
    cmd.extend(["--prefix", config.prefix])

    # MPNN options
    cmd.extend(["--mpnn_runner", str(config.mpnn.mpnn_runner)])
    cmd.extend(["--model_type", config.mpnn.model_type])
    cmd.extend(["--temperature", str(config.mpnn.temperature)])
    cmd.extend(["--number_of_batches", str(config.mpnn.number_of_batches)])
    cmd.extend(["--batch_size", str(config.mpnn.batch_size)])

    if config.mpnn.enhance_model:
        cmd.extend(["--enhance", config.mpnn.enhance_model])
    else:
        cmd.append("--no_enhance")

    if config.mpnn.pack_side_chains:
        cmd.append("--pack_side_chains")

    cmd.extend(["--sc_num_denoising_steps", str(config.mpnn.sc_num_denoising_steps)])
    cmd.extend(["--omit_AA", config.mpnn.omit_AA])

    if config.mpnn.use_apptainer:
        cmd.append("--use_apptainer")
        cmd.extend(["--apptainer_image", str(config.mpnn.apptainer_image)])

    # Constraints
    cmd.extend(["--primary_contact_cutoff", str(config.constraints.primary_contact_cutoff)])
    cmd.extend(["--secondary_contact_cutoff", str(config.constraints.secondary_contact_cutoff)])
    cmd.extend(["--metal_cutoff", str(config.constraints.metal_cutoff)])
    cmd.extend(["--coord_cst_weight", str(config.constraints.coord_cst_weight)])
    cmd.extend(["--coord_cst_stdev", str(config.constraints.coord_cst_stdev)])

    if config.constraints.ref_pdb:
        cmd.extend(["--ref_pdb", str(config.constraints.ref_pdb)])
    if config.constraints.cst_file:
        cmd.extend(["--cst_file", str(config.constraints.cst_file)])

    # Relax
    cmd.extend(["--scorefunction", config.relax.scorefunction])
    cmd.extend(["--fastrelax_cycles", str(config.relax.fastrelax_cycles)])
    cmd.extend(["--mobile_radius", str(config.relax.mobile_radius)])
    cmd.extend(["--cart_bonded_weight", str(config.relax.cart_bonded_weight)])

    if config.relax.use_pyrosetta:
        cmd.append("--use_pyrosetta")
    if config.relax.weight_flexibility:
        cmd.append("--weight_flexibility")

    if config.relax.use_pyrosetta_image:
        cmd.append("--use_pyrosetta_image")
        cmd.extend(["--pyrosetta_image", str(config.relax.pyrosetta_image)])
    else:
        cmd.append("--no_pyrosetta_image")

    # Catres
    if config.catres.catres_subset:
        cmd.extend(["--catres_subset", ",".join(map(str, config.catres.catres_subset))])
    if config.catres.redesign_non_subset_catres:
        cmd.append("--redesign_non_subset_catres")

    # Pipeline
    cmd.extend(["--n_cycles", str(config.pipeline.n_cycles)])
    cmd.extend(["--n_candidates", str(config.pipeline.n_candidates)])
    cmd.extend(["--n_keep", str(config.pipeline.n_keep)])
    cmd.extend(["--n_final", str(config.pipeline.n_final)])
    cmd.extend(["--design_shell_radius", str(config.pipeline.design_shell_radius)])
    if not config.pipeline.fix_outside_shell:
        cmd.append("--no_fix_outside_shell")

    # Execution
    if config.single_thread:
        cmd.append("--single_thread")
    if config.verbose:
        cmd.append("--verbose")

    if config.log_file:
        cmd.extend(["--log_file", str(config.log_file)])

    return shlex.join(cmd)


def generate_array_sbatch(
    pdb_list: List[Path],
    output_dir: Path,
    params_files: List[Path],
    slurm_config: Optional[SlurmConfig] = None,
    base_config: Optional[RunConfig] = None,
    job_name: str = "fastmpnn_array"
) -> Path:
    """
    Generate sbatch array job script for processing multiple PDBs.

    Args:
        pdb_list: List of input PDB paths.
        output_dir: Base output directory.
        params_files: Params files to use for all jobs.
        slurm_config: SLURM configuration.
        base_config: Base run configuration to use.
        job_name: Job name.

    Returns:
        Path to generated sbatch script.
    """
    if slurm_config is None:
        slurm_config = SlurmConfig()

    output_dir = Path(output_dir)
    ensure_dir(output_dir)

    # Write PDB list file
    list_file = output_dir / "pdb_list.txt"
    with open(list_file, 'w') as f:
        for pdb in pdb_list:
            f.write(f"{pdb}\n")

    n_jobs = len(pdb_list)

    # Build partition line
    partition_line = ""
    if slurm_config.partition:
        partition_line = f"#SBATCH --partition={slurm_config.partition}"

    # Params string
    params_str = " ".join(f"--params {p}" for p in params_files)

    script = f"""#!/bin/bash
#SBATCH --job-name={job_name}
#SBATCH --output={output_dir}/logs/{job_name}_%A_%a.out
#SBATCH --error={output_dir}/logs/{job_name}_%A_%a.err
#SBATCH --time={slurm_config.time}
#SBATCH --cpus-per-task={slurm_config.cpus}
#SBATCH --mem={slurm_config.mem}
#SBATCH --array=1-{n_jobs}
{partition_line}

# FastMPNN Design Array Job
# Generated by fastmpnndesign
# Processing {n_jobs} PDB files

echo "Array task $SLURM_ARRAY_TASK_ID of $SLURM_ARRAY_TASK_COUNT"
echo "Starting at $(date)"

# Get PDB for this task
PDB=$(sed -n "${{SLURM_ARRAY_TASK_ID}}p" {list_file})
BASENAME=$(basename "$PDB" .pdb)
JOB_OUTPUT_DIR="{output_dir}/$BASENAME"

echo "Processing: $PDB"
echo "Output to: $JOB_OUTPUT_DIR"

# Run fastmpnndesign
fastmpnndesign \\
    --pdb "$PDB" \\
    {params_str} \\
    --output_dir "$JOB_OUTPUT_DIR" \\
    --prefix "$BASENAME" \\
    --verbose

EXIT_CODE=$?

echo "Task completed at $(date) with exit code $EXIT_CODE"
exit $EXIT_CODE
"""

    # Create logs directory
    ensure_dir(output_dir / "logs")

    # Write script
    script_path = output_dir / f"{job_name}.sbatch"
    with open(script_path, 'w') as f:
        f.write(script)
    script_path.chmod(0o755)

    logger.info(f"Generated array sbatch script: {script_path}")
    logger.info(f"  Will process {n_jobs} PDB files")

    return script_path


def submit_job(sbatch_script: Path, dry_run: bool = False) -> Optional[str]:
    """
    Submit sbatch script to SLURM.

    Args:
        sbatch_script: Path to sbatch script.
        dry_run: If True, print command without submitting.

    Returns:
        Job ID if submitted, None if dry run or failed.
    """
    import subprocess

    cmd = ["sbatch", str(sbatch_script)]
    cmd_str = " ".join(cmd)

    if dry_run:
        logger.info(f"Dry run: {cmd_str}")
        return None

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=30
        )

        if result.returncode == 0:
            # Parse job ID from output like "Submitted batch job 12345"
            output = result.stdout.strip()
            parts = output.split()
            if len(parts) >= 4:
                job_id = parts[-1]
                logger.info(f"Submitted job: {job_id}")
                return job_id
            return output
        else:
            logger.error(f"sbatch failed: {result.stderr}")
            return None

    except Exception as e:
        logger.error(f"Failed to submit job: {e}")
        return None
